### ISSUE TITLE
Cut down on blockstates by incrementing randomly

### ISSUE THREAD

**Issue by sargunv** [matjojo/desire-paths#1]
Instead of bumping the trample state every tick a block is walked on, you could increment it on, say, 10% of ticks and convert at 4 instead of 20. Bonus points for the increment probability and trample state blockstate count to be configurable.

**Comment by matjojo** [comment]
Will be added in the 14.2 version, and is already done, seeing that pre-4 was today 14.2 should be somewhere next week
