### ISSUE TITLE
Don't change blocks that have sugarcane on it.

### ISSUE THREAD

**Issue by matjojo** [matjojo/desire-paths#2]
Don't change blocks that have sugarcane on it.

**Comment by matjojo** [comment]
Another option might be to allow sugarcane on trampled blocks, but that might be a rabbit hole of problems

**Comment by matjojo** [comment]
Left problem is that trampled mycelium can carry sugarcane even though mycelium itself cannot, I find this no problem, just imagine that the cane is on top of the trampled parts.

**Comment by Arkhayla** [comment]
This impacts saplings as well. Additionally, you can't plant saplings on grass that's been trampled at all or even dirt you've walked on. This makes replanting a harvested tree farm very difficult.

**Comment by matjojo** [comment]
I hadn't thought of saplings yet, will take a look.

**Comment by matjojo** [comment]
@Arkhayla This will be fixed in the following version, I will release it at the same time I'm ready to support 14.3, which should drop soon.

This is a generic solution, so this should fix it for almost all plants, I haven't seen any other plants in code that this does not support yet, but if there are any other and you notice it please do report it of course.
