### ISSUE TITLE
Breaking blocks is at a different speed?

### ISSUE THREAD

**Issue by matjojo** [matjojo/desire-paths#20]

**Comment by Arkhayla** [comment]
Tested on the latest version (1.3.0 - 1.14.2) and can confirm this happens for me too. No efficiency on the shovel in use

**Comment by matjojo** [comment]
@Arkhayla This will be fixed in the next version

**Comment by Arkhayla** [comment]
Appreciate you @matjojo - If my comments or bug reports ever become overwhelming just say so hehe

**Comment by matjojo** [comment]
Nah no problem. Those reports are valuable to me!
