### ISSUE TITLE
Enable tilling and turning into grass path with shovel.

### ISSUE THREAD

**Issue by nerdshark** [matjojo/desire-paths#21]
Blocks that have been trampled can't be turned into grass path or farmland blocks.

**Comment by matjojo** [comment]
This should work since 1.2.0, what version are you using?

**Comment by nerdshark** [comment]
Sorry, I'm on 1.3.0. Just updated.

**Comment by nerdshark** [comment]
Okay, weird, it's working now. I think I may have been doing something wrong.

**Comment by matjojo** [comment]
If that meant that it works now, good, otherwise, are you using any other
mods, are you using a tool from another mod? Are you sure you are not
trying to turn dirt itself, which can't be flattened into path anyway?

**Comment by nerdshark** [comment]
I *was* previously unable to till dirt blocks with 1.2.0, but that's working now. And yeah, I was also trying to flatten a dirt block. Flattening trampled grass is also working. Not using tools from other mods, just the standard hoe.

**Comment by matjojo** [comment]
Good to hear.
