### ISSUE TITLE
Underside texture

### ISSUE THREAD

**Issue by Luxlator** [matjojo/desire-paths#22]
![2019-06-01_15 34 26](https://user-images.githubusercontent.com/51272308/58752784-d3784400-8482-11e9-8c92-e8a5f0e70b35.png)
![2019-06-01_15 34 38](https://user-images.githubusercontent.com/51272308/58752785-d3784400-8482-11e9-9f0b-ff909c06c23b.png)

I'm using version 1.1.0 from Curse Forge

The underside of the block has the side texture of a grass block.

**Comment by matjojo** [comment]
Yep, I know, got fixed some versions back. Newest version definitely does
not have that issue. If you need me to backport the issue to any older
Minecraft version (1.14 only ofc)I'll make a jar for you

**Comment by matjojo** [comment]
Now that I am at my pc again I can verify that this was fixed in 1.2.0. And is also not a problem in later versions.
