### ISSUE TITLE
Trampled dirt / grass has much slower dig speed than original counterpart, and different break sound

### ISSUE THREAD

**Issue by loadstarnes** [matjojo/desire-paths#23]

**Comment by matjojo** [comment]
Speed is already fixed for next version, which I will release with 14.3, but sound I'll look into

**Comment by loadstarnes** [comment]
Excellent. Also be sure to check out walk-sounds!

I love the immersion this mod brings. Thank you.

**Comment by matjojo** [comment]
It took me a while, but I finally could find some time to test and release, the walking sounds are on my list to check out later, sorry I couldn't get to it earlier.
Download here: https://www.curseforge.com/minecraft/mc-mods/desire-paths/files/2734879
