### ISSUE TITLE
Grass not regrowing

### ISSUE THREAD

**Issue by JJSax** [matjojo/desire-paths#26]
I can't seem to get any level of grass to grow back more than one level.

I made a large platform of bare dirt to test if grass would grow on it's own or if it needs adjacent grass and what level it needs to be.  I put random tick speed to 30, 300 then 30000 (default is 3).  I could only get any level of grass to go up one level then it was stuck.  the first change happens quickly with random tick acceleration. 

version 1.2.8
forge version 14.23.5.2838

**Comment by matjojo** [comment]
This is a fabric mod, it will not work with forge. There are some projects
to get forge mods running on fabric, but the other way around not as far as
I know.

There was a 1.12 forge desirepath mod, the author might want to update that
one if forge is already up to date till 1.14, I must be honest I don't know
if it is.
