### ISSUE TITLE
Backport to Forge 1.12.2?

### ISSUE THREAD

**Issue by Geezt435** [matjojo/desire-paths#32]
This might be a pain but can you please backport to Forge Minecraft version 1.12.2? It looks highly configurable and customizable for a mod pack

**Comment by matjojo** [comment]
Thanks for being interested in my mod!

This mod has exactly 0 configuration options rn. And it runs on Fabric. I don't like the way the forge people are at this moment so will probably not be using forge anytime soon.

Regardless, there is already a 1.12.2 Forge desirepaths mod over at https://www.curseforge.com/minecraft/mc-mods/desirepaths

I'm not sure if that one does have settings etc, but as long as the fabric lads have not stopped bikeshedding their own settings API I don't really wanna spend the time doing it myself.
